server:
  port: 8091

spring:
  appliction:
    name: Spring Security Demo
  # 当前环境设置 dev开发环境 test测试环境 prod生产环境
  profiles:
    active: dev
  # MySql 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: yuzhijie1218
    driver-class-name: com.mysql.jdbc.Driver
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  #配置mapper xml文件的路径
#    mybatis-plus:
#      mapper-locations:
#        classpath: com/imufe/TestSystem/mapper/xml/*.xml

